# Generated by Django 3.2.8 on 2022-07-24 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('name', models.CharField(max_length=26)),
                ('parameters', models.CharField(max_length=52)),
                ('pytorch', models.CharField(blank=True, max_length=52, null=True)),
                ('pennylane', models.CharField(blank=True, max_length=52, null=True)),
                ('tensorflow', models.CharField(blank=True, max_length=52, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('name', models.CharField(max_length=26)),
                ('type', models.CharField(max_length=26)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('graph', models.CharField(max_length=52)),
                ('layers', models.CharField(max_length=52)),
                ('loss', models.CharField(blank=True, max_length=26, null=True)),
                ('weights', models.CharField(blank=True, max_length=52, null=True)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
