# Generated by Django 3.2.8 on 2022-08-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(max_length=26, unique=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='parameters',
            field=models.CharField(max_length=676),
        ),
        migrations.AlterField(
            model_name='layer',
            name='pennylane',
            field=models.CharField(blank=True, max_length=17576, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='pytorch',
            field=models.CharField(blank=True, max_length=17576, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='tensorflow',
            field=models.CharField(blank=True, max_length=17576, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='graph',
            field=models.CharField(max_length=456976),
        ),
        migrations.AlterField(
            model_name='network',
            name='layers',
            field=models.CharField(max_length=456976),
        ),
        migrations.AlterField(
            model_name='network',
            name='weights',
            field=models.CharField(blank=True, max_length=676, null=True),
        ),
    ]
